config/routes.rb
Rails.application.routes.draw do

  root :to => "welcome#index"
  resources :issue do
  	collection do
        post 'issues_rows'
      end
  end
end

app/models/add_settings_to_repostore.rb
class AddSettingsToRepostore < ActiveRecord::Base
  def up
    add_column :repostores, :settings, :hstore
  end

  def down
    remove_column :repostores, :settings
  end
end

app/models/repostore.rb
class Repostore < ActiveRecord::Base
 store_accessor :settings

 def redis_key(str)
   "#{self.name}:#{self.id}:#{str}"
 end

 def get_value(key)
      issues_list = $redis.get(self.redis_key(key.to_sym))
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/issue_controller.rb
class IssueController < ApplicationController

 TOTAL_OPEN = "Total open issues"
 PAST_24 = "Issues opened in past 24 hrs"
 BET_24_7 = "Issues opened more than 24 hours ago but less than 7 days ago"
 MORE_THAN_7 = "Issues opened more than 7 days ago"
 def index
  token = $GIT_TOKEN

  @owner, @repo = params[:user].split('/')
  git_client = Github.new auto_pagination: true, oauth_token: token, user: @owner, repo: @repo
  repos = git_client.repos.list.collect(&:full_name)
  if repos && repos.map{|s| s.downcase}.include?(params[:user])
   @repostore = Repostore.where(name: "#{@owner}.#{@repo}").first
   @repostore = Repostore.new(name: "#{@owner}.#{@repo}") unless @repostore
   values_hash = get_issues(@owner, @repo, git_client)
   update_store(values_hash)
   make_calculations
  else
   flash[:notice] = "Repo doesnt exist"
   redirect_to :back
  end
 end

 def issues_rows
  @repostore = Repostore.find(params[:repostore_id])
  @issue_name = params[:submit]
     @display =  JSON.parse $redis.get(@repostore.redis_key(@issue_name.to_sym))
    @display.map!{ |h| h.slice("html_url", "id", "user", "title")}
     respond_to do |format|
         format.js { render :layout => false }
     end
 end

 def get_issues(owner, repo, git_client, options={})
  @issues_list = git_client.issues.list(user: owner, repo: repo, state: "open")
  @issues_last_24_hours = git_client.issues.list(user: owner, repo: repo, state: "open", filter: 'created', since: Time.parse("#{1.days.ago}").iso8601)
  @issues_last_7_days = git_client.issues.list(user: owner, repo: repo, state: "open", filter: 'created', since: Time.parse("#{7.days.ago}").iso8601)
  
  values_hash = {
   issues_list: @issues_list,
   issues_last_24_hours: @issues_last_24_hours,
   issues_last_7_days: @issues_last_7_days,
   table_data: @table_data
  }

  @table_data = {
   "Total open issues" => @issues_list.size,
   "Issues opened in past 24 hrs" => @issues_last_24_hours.size,
   "Issues opened more than 24 hours ago but less than 7 days ago" => @issues_last_7_days.size - @issues_last_24_hours.size,
   "Issues opened more than 7 days ago" => @issues_list.size - @issues_last_7_days.size
  }
  values_hash
 end
 

 def update_store(values_hash)
  @repostore.save
  $redis.multi do
   values_hash.each do |k,v|
    $redis.set(@repostore.redis_key(k.to_sym), v.to_json)
   end
  end
 end

 def make_calculations
  hash_data = {}
  [:issues_list, :issues_last_24_hours, :issues_last_7_days].each{|key| hash_data[key] = JSON.parse ($redis.get(@repostore.redis_key(key.to_sym)))}
  hash_data[TOTAL_OPEN] = (hash_data[:issues_list])
  hash_data[PAST_24] = (hash_data[:issues_last_24_hours])
  hash_data[BET_24_7] = (hash_data[:issues_last_7_days]) - (hash_data[:issues_last_24_hours])
  hash_data[MORE_THAN_7] = (hash_data[:issues_list])- (hash_data[:issues_last_7_days])
  hash_data.each do |k,v|
   $redis.set(@repostore.redis_key(k.to_sym), v.to_json)
  end
 end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

 def index
 end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/issue_helper.rb
module IssueHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/issue/_issue_details.erb
<div class="row">
<div class="col-md-4 col-md-offset-4">
 <table class="table table-bordered table-striped">
   <thead>
     <tr>
       <th>Issue ID</th>
       <th>Username</th>
       <th>Title</th>
     </tr>
   </thead>
   <tbody>
   
     <% @display.each do |record| %>
       <tr>
         <td><%= record["id"] %></td>
         <td><%= record["user"]["login"] %></td>
         <td><%= link_to record["title"], record["html_url"]  %></td>
       </tr>
     <% end %>
   </tbody>
 </table>
</div>
</div>

app/views/issue/index.html.erb
<div class="row">
  <div class="col-md-4 col-md-offset-4">
   <div class='text-center'>
    <p><b>Click on Links to view issues</b></p>
   </div>
    <table class="table table-bordered table-striped">
      <thead>
        <tr>
          <th>Timeline</th>
          <th>No of Issues</th>
        </tr>
      </thead>
      <tbody>
      
        <% @table_data.each do |issue, value| %>
          <tr>
            <td><%= link_to issue, {:action => :issues_rows, :submit => issue, :repostore_id => @repostore.id}, {method: :post, :remote => true, :id=>"clk", dataType: 'json'} %></td>
            <td><%= value %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<div id="allclick">
    <%= render :partial => 'issue_details' if @display.present? %>
</div>

app/views/issue/issues_rows.js.erb
$("#allclick").html("<%= escape_javascript(render(:partial => "issue_details")) %>");

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GitTrack</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<div class="row">
 <div class="col-lg-6 col-lg-offset-3 text-center">
  <p id="notice"><%= flash[:notice] %></p>
  <h2><b>Gitbug Issues Viewer</b></h2>
 </div>
 <div class="col-lg-6 col-lg-offset-3 text-center">
   <%= form_tag(issue_index_path, :method => "get", class: "navbar-form") do %>
         <div class="form-group">
             <label for="code">GithubUser/Repo</label>
             <input type="text" name='user' id='user' value="shippable/support" class="form-control input-lg">
         </div>
         <button type="submit" class="btn btn-default">Submit</button>
   <% end %>
   </div>
</div>